name: Release

on:
  pull_request:
    types: [closed]

jobs:
  release:
    if: ${{ startsWith( ${{ github.event.pull_request.title }} , 'v') }}
    name: release ${{ github.event.pull_request.title }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create a new release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.pull_request.title }}
          release_name: Release ${{ github.event.pull_request.title }}
          draft: false
          prerelease: false
